[package]
name = "gearly"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
axum = { version = "0.8", features = ["macros"] }
diesel = { version = "2.3.11", features = ["mysql", "chrono"] }
dotenv = "0.15.0"
serde = "1.0.228"
sqlx = {version = "0.9.0", features = ["mysql", "macros"]}
tokio = {version = "1.52.3", features =["full"]}
rand_core = { version = "0.6.4", features = ["getrandom"] }
chrono = "0.4.45"
validator = "0.21.0"
reqwest = { version = "0.13.4", features = ["json"] }
lettre = { version = "0.11", features = ["smtp-transport", "tokio1", "tokio1-native-tls"] }
jsonwebtoken = { version = "11.0.0", features = ["aws_lc_rs"]}
thiserror = "2.0.20"
